name: Build

on: [pull_request, push]

permissions:
  contents: write

jobs:
  release:
    name: Release
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v8
        with:
          BRANCH_NAME: releases/${MAJOR}
          CLEAN_TARGETS: '.gitignore,.github,*.lock,*.json'
          COMMIT_MESSAGE: 'Build: release ${{ github.ref_name }} via ${{ github.sha }}'
